---
- hosts: nfs
  become: yes
  tasks:
    - name: install the TOOLS
      dnf:
        name:
          - nfs-utils
          - net-tools
          - nfs4-acl-tools 
          - wget
        state: latest

    - name: Enable NFS-SERVER on all nodes
      shell: systemctl  enable nfs-server

    - name: Start NFS-SERVER on all nodes
      shell: systemctl start nfs-server

    - name: Creating srv/nfs on all nodes
      shell: mkdir /srv/nfs

    - name: config nfs share access
      copy:
        dest: "/etc/exports"
        content: |
          /srv/nfs	10.0.1.10(rw,sync)
          /srv/nfs	10.0.1.11(rw,sync)
          /srv/nfs	10.0.1.12(rw,sync)
      register: output_nfs

    - debug:
        vars: output_nfs.stdout_lines

    - name: apply nfs share config
      shell: |
        exportfs -r
        exportfs -s
      register: output_exportsfs

    - debug:
        vars: output_exportsfs.stdout_lines

    - name: add firewall policies
      shell: |
        firewall-cmd --permanent --add-service=nfs
        firewall-cmd --permanent --add-service=rpc-bind
        firewall-cmd --permanent --add-service=mountd
        firewall-cmd --reload
      register: output_policies

    - debug:
        vars: output_exportsfs.stdout_lines
